### ISSUE TITLE
Change license to MIT

### ISSUE THREAD

**Issue by erwan-joly** [NosCoreIO/NosCore.Packets#63]
Change license to MIT
- [x] @0Lucifer0
- [x] @BlowaXD
- [x] @Elendan
- [x] @ApourtArtt
- [x] @Adanlink
- [x] @senterol
- [x] @Zagith
- [x] @Bari77

Can you please tell me if you agree with License moving to MIT
Will wait till 1 of july and move to MIT except if somebody is against that

**Comment by Adanlink** [comment]
I don't see any reason to move it to MIT honestly, I decline unless there is a good reason.

**Comment by Bari77** [comment]
That's not a problem for me.

**Comment by 0Lucifer0** [comment]
@Adanlink Because that would allow people with private projects to use it legally. I don’t want to enforce GPL but I don’t like to see everybody breaking this license policies

**Comment by 0Lucifer0** [comment]
Moreover it often helps to get free license for tools like resharper

**Comment by Zagith** [comment]
Yeah, i agree too,

**Comment by senterol** [comment]
Fine for me ^^

**Comment by Adanlink** [comment]
> @Adanlink Because that would allow people with private projects to use it legally. I don’t want to enforce GPL but I don’t like to see everybody breaking this license policies

Using NosCore.Packet's source code for doing your own version is legal with GPL3, what is not allowed (without going too deep) is to distribute it without the same license or in other words, the source code (with distribute it can mean selling/sharing/publishing).

Maybe MIT would make more attractive to contribute to the project, but with the cancerous scene of NosTale I doubt it will help, it could even make it worst.

Also, I don't understand why it would help to get tools, GPL3 is valid here https://opensource.org/docs/osd as MIT is too.

**Comment by Elendan** [comment]
Tbh, I don't see the point, but I don't see the problem either. Enforcing the GPL in a waste of time, the NosTale community doesn't give a shoot about the licence type as long as they can leech.  

Also, there is probably no server owner around that is able to pull a nuget package to use the NosCore.Packets library so I don't see why the type licence matters so much

**Comment by ApourtArtt** [comment]
Sure, go for it !

**Comment by erwan-joly** [comment]
Last time I asked for free license I’ve seen in case of MIT and Apache everything is automatic. In case of GPL they manually review it and it need multiple emails. Most of the free licenses are only valid for 1 year and I would like to refresh this as easily as I can

**Comment by 0Lucifer0** [comment]
Last time I asked for free license I’ve seen in case of MIT and Apache everything is automatic. In case of GPL they manually review it and it need multiple emails. Most of the free licenses are only valid for 1 year and I would like to refresh this as easily as I can

**Comment by 0Lucifer0** [comment]
@Adanlink after checks it seems like it’s actually Apache not MIT For jetbrains
However that doesn’t really change the fact that in the end the GPL is not respected at all and that nobody will enforce it. So letting people do whatever they want as long as authors are still defined seems better to me

**Comment by Adanlink** [comment]
Maybe I'm wrong, but what does people not enforce? The majority of people (to not say all of which I have heared) that distributes (principally sells) "reflavored" versions of Opennos (for example) gives it with the source code (as established with the GPL2 license) and not a compiled version or worst, an obfuscated one.

I really think that this change of license is not positive as it would only worsen the possible future contributions to it (because as it is known, people leaches a lot, and it would even worsen if they could sell their private versions of NosCore without the source code, as it would allure to the doing of those private versions).

**Comment by 0Lucifer0** [comment]
I’ve seen multiple release done as non GPL, leak of real developers work by leechers and some people even changed the license. With mit the few real dev of the community can sell their change under a private copyrighted license if they want to do it and they can sue anybody who would release it without consent. 
Won’t change much technically moreover noscore itself will be difficult to change as it has lot more contributors (even if most of them are for translations and those are going to disappear)

**Comment by 0Lucifer0** [comment]
@Adanlink the main goal is to let real developers have the power over what they are creating. 
there are better example out there with people who didnt even have coded anything but for example : https://www.elitepvpers.com/forum/nostale/4645443-release-opennos-sources.html
_Its OpenNos so i have the right to publish this shitty Sources without that i should care if someone wanna it or not._
this is the kind of behavior i'm trying to prevent here

**Comment by 0Lucifer0** [comment]
i want real dev to have the choice of their licenses

**Comment by BlowaXD** [comment]
> 
> 
> @Adanlink the main goal is to let real developers have the power over what they are creating.
> there are better example out there with people who didnt even have coded anything but for example : https://www.elitepvpers.com/forum/nostale/4645443-release-opennos-sources.html
> _Its OpenNos so i have the right to publish this shitty Sources without that i should care if someone wanna it or not._
> this is the kind of behavior i'm trying to prevent here

Let's be realistic, no single dev in this community will ever sue anyone for leaking its work.

Especially that, given NosCore's design, instead of making a community-centric project, you are encouraging people to make their own fork of NosCore, which will end being not interoperable between every other NosCore forks versions (like already done on OpenNos, many forks and some piece of code are not interoperable with the different forks online), which fucks up the idea of an opensource community driven project.

If you want my feedback, do whatever you want, I don't care, this community does not deserve anything from my point of view and I would rather delete my work rather than making public.
